### ISSUE TITLE
Backslashes are removed from cloned pages

### ISSUE THREAD

**Issue by hkoren** [cncf/clone-page-tree#1]
As part of the cloning process, the cloned page contents are mangled by the removal of backslashes

**Comment by hkoren** [comment]
changing:
$new_post_id = wp_insert_post($args);
to:
$new_post_id = wp_insert_post(wp_slash( $args) );
addressed this issue

**Comment by cjyabraham** [comment]
Thanks for reporting this.  Fixed and [released as v0.1.1](https://wordpress.org/plugins/clone-page-tree/).
